language: c

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=luajit
    # - LUA=luajit2.0
    # - LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install busted

script:
  - busted test/*.lua

